approvedGitRepositories:
  - "https://github.com/cozy/*"
  - "https://github.com/linagora/*"
  - "https://github.com/konnectors/*"

compressionLevel: mixed

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - "@linagora/*"
  - "@cozy/*"
  - cozy-*
  - twake-*
  - babel-preset-cozy-app
  - rsbuild-config-cozy-app
  - stylus-config-cozy-app
  - browserslist-config-cozy
